notifications:
  email: false

language: node_js

node_js:
- node

env:
  global:
  - BUILD_PATH=dist
  matrix:
  - ENV=development
  - ENV=production NODE_ENV=production

cache:
  directories:
  - node_modules

before_script:
- openssl aes-256-cbc -k $ENCRYPTION_KEY -in .npmrc.enc -out .npmrc -d

script:
- npm run build

deploy:
- provider: pages
  local_dir: $BUILD_PATH
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    condition:
    - $ENV = production
